import React, { createContext, useState, useContext, ReactNode } from 'react';

type Language = 'en' | 'tr';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const translations: Record<Language, Record<string, string>> = {
    en: {
        "nav.home": "Home",
        "nav.products": "Products",
        "nav.locations": "Locations",
        "nav.careers": "Careers",
        "nav.about": "About Us",
        "nav.contact": "Contact",
        "nav.requestQuote": "REQUEST QUOTE",

        "hero.title": "Perfection From The Mountain",

        "hero.cta": "Explore the Collection",

        "intro.title": "DIGITAL LAPIDARIUM",
        "intro.text": "Bringing nature's unique art into your living spaces. Our natural stone collection, selected for its distinct texture and character, adds timeless elegance and a sophisticated atmosphere to your spaces.",
        "intro.stat1Label": "ANNUAL EXTRACTION",
        "intro.stat2Label": "QUARRY AREA",
        "intro.stat3Label": "EXPORT",
        "intro.stat3Unit": "COUNTRIES",

        "catalog.curated": "Curated Slabs",
        "catalog.scroll": "Scroll Catalog",

        "showroom.virtual": "Seemar Natural Stone & Marble",
        "showroom.title": "VIRTUAL SHOWROOM EXPLORATION",
        "showroom.text": "Immerse yourself in our meticulously designed virtual showrooms. Discover marble applications in a dynamic 3D isometric view, with clickable markers revealing precise specifications and design insights.",
        "showroom.cta": "Start Virtual Tour",

        "projects.label": "PROJECTS",
        "projects.title": "Architectural Masterpieces",
        "projects.viewAll": "View All Projects",
        "projects.all": "All",
        "projects.commercial": "Commercial",
        "projects.residential": "Residential",
        "projects.hospitality": "Hospitality",
        "projects.religious": "Religious",
        "projects.art": "Art & Sculpture",
        "projects.pageDesc": "Explore our portfolio of prestigious architectural projects featuring SeeMAR natural stone. From sacred spaces to commercial landmarks, each project tells a story of craftsmanship and permanence.",
        "projects.filter": "Filter By:",
        "projects.empty": "No projects found in this category.",
        "projects.featured": "Featured",
        "projects.ctaTitle": "Have a Project in Mind?",
        "projects.ctaDesc": "Let our team bring your architectural vision to life with premium Turkish stone.",
        "projects.ctaButton": "Start Your Project",
        "projects.location": "Location",
        "projects.year": "Year",
        "projects.materials": "Materials Used",
        "projects.client": "Client",
        "projects.viewProject": "View Project",
        "projects.backToProjects": "Back to Projects",
        "projects.relatedProjects": "Related Projects",
        "projects.aboutProject": "About This Project",
        "projects.projectDetails": "Project Details",
        "projects.projectNotFound": "Project Not Found",

        "catalog.label": "E-CATALOG",
        "catalog.title": "Product Catalog",
        "catalog.desc": "Explore our complete collection of natural stones, marbles, and architectural materials in our digital catalog.",
        "catalog.pdfTitle": "Seemar Product Catalog 2024",
        "catalog.download": "Download PDF",
        "catalog.loading": "Loading catalog...",
        "catalog.noteTitle": "Note",
        "catalog.noteText": "This digital catalog provides an overview of our standard collection. For rare specimens, custom cuts, and exclusive materials, please contact our sales team directly.",

        "products.collection": "The Collection",
        "products.title": "Stone Library",
        "products.desc": "Explore our curated selection of raw chaos refined into polished perfection. Each slab is a unique page in the geological history of our earth.",
        "products.filter": "Filter By:",
        "products.empty": "No specimens found in this category.",
        "products.reset": "Reset Filter",
        "products.customTitle": "Custom Cuts Available",
        "products.customDesc": "Looking for something specific? We offer custom cuts, special dimensions, and exclusive stone varieties tailored to your project needs.",
        "products.requestAccess": "Request Private Access",

        // Product Categories
        "cat.marble": "Marble",
        "cat.travertine": "Travertine",
        "cat.onyx": "Onyx",
        "cat.limestone": "Limestone",
        "cat.granite": "Granite",
        "cat.dolomite": "Dolomite",
        "cat.mosaic": "Mosaic",
        "cat.splitface": "Split Face",
        "cat.tumbled": "Tumbled Stone",
        "cat.sand": "Industrial Sand",
        "cat.all": "All Collections",

        "careers.join": "Join Our Legacy",
        "careers.heroDesc": "Crafting the future of stone with art. Where brutalist precision meets organic art.",
        "careers.artTitle": "The Art of Permanence",
        "careers.artDesc1": "At SeeMAR, we don't just cut stone; we curate history. We are looking for artisans and engineers who understand the weight of permanence.",
        "careers.artDesc2": "Our culture is a balance of brutalist precision and organic creativity. Whether you are operating a 5-axis CNC machine or hand-polishing a slab of Carrara, your work contributes to a legacy set in stone.",
        "careers.openings": "Current Openings",
        "careers.openingsDesc": "Join the Digital Lapidarium team.",
        "careers.apply": "Apply Now",

        "footer.desc": "Blending nature's soul with aesthetics. A legacy carved in stone, delivering timeless elegance to the world's most prestigious projects.",
        "footer.explore": "Explore",
        "footer.company": "Company",
        "footer.social": "Social",
        "footer.rights": "All rights reserved.",
        "footer.quarryHQ": "Quarry HQ",
        "footer.theCollection": "The Collection",
        "footer.rareFinds": "Rare Finds",
        "footer.projects": "Projects",
        "footer.journal": "Journal",
        "footer.sustainability": "Sustainability",
        "footer.privacyPolicy": "Privacy Policy",
        "footer.termsOfUse": "Terms of Use",
        "footer.pdfCatalog": "PDF Catalog",

        "careers.precision": "Precision",
        "careers.heritage": "Heritage",
        "careers.innovation": "Innovation",
        "careers.allRoles": "All Roles",
        "careers.artisans": "Artisans",
        "careers.engineering": "Engineering",
        "careers.operations": "Operations",
        "careers.dontSeeVein": "Don't see your vein?",
        "careers.talentText": "We are always looking for exceptional talent to join our quarry of experts. Send us your portfolio or CV.",
        "careers.contactUs": "Contact Us",
        "careers.coverLetter": "Cover Letter (Optional)",
        "careers.coverLetterPlaceholder": "Tell us why you are the perfect fit for this role...",
        "careers.breadcrumb": "Careers",
        "careers.jobDetails": "Job Details",
        "careers.division": "Division",
        "careers.applyNow": "Apply Now",
        "careers.theRole": "The Role",
        "careers.responsibilities": "Responsibilities",
        "careers.qualifications": "Required Qualifications",
        "careers.applyForPosition": "Apply for this position",
        "careers.applyDesc": "Submit your application to start your journey with SeeMAR.",
        "careers.firstName": "First Name",
        "careers.lastName": "Last Name",
        "careers.email": "Email Address",
        "careers.phone": "Phone",
        "careers.linkedin": "LinkedIn Profile (Optional)",
        "careers.resume": "Resume / CV",
        "careers.uploadResume": "Upload Resume",
        "careers.submitApplication": "Submit Application",
        "careers.fileSizeError": "File Size Limit Exceeded (Max 5MB)",
        "careers.aboutTeam": "About the Team",
        "careers.defaultTeamDesc": "Join a team of dedicated professionals.",
        "careers.keyBenefits": "Key Benefits",
        "careers.benefit1": "Comprehensive Health Coverage",
        "careers.benefit2": "Retirement Pension Plan",
        "careers.benefit3": "Daily Organic Canteen",
        "careers.benefit4": "Annual Masterclass Stipend",
        "careers.shareRole": "Share this role",
        "careers.similarRoles": "Similar Roles",
        "careers.similarRolesDesc": "Explore other opportunities in the Digital Lapidarium.",
        "careers.viewAllOpenings": "View All Openings",
        "careers.detailsOnApplication": "Details available upon application.",

        "quote.title": "Request A Quote",
        "quote.desc": "Specify your project requirements to receive a detailed proposal tailored to your architectural vision. We provide custom quotes for quarry-direct materials.",
        "quote.step1": "Contact Information",
        "quote.step2": "Project Details",
        "quote.step3": "Project Location",
        "quote.step4": "Additional Notes",
        "quote.submit": "Submit Quote Request",
        "quote.fromQuarry": "From The Quarry",
        "quote.rawMaterial": "Raw Material.",
        "quote.refinedElegance": "Refined Elegance.",
        "quote.needAssistance": "Need Assistance?",
        "quote.assistanceDesc": "Our stone curators are available to guide your selection for architectural projects.",
        "quote.collection": "The Collection",
        "quote.fullName": "Full Name",
        "quote.fullNamePlaceholder": "Enter your full name",
        "quote.companyName": "Company Name",
        "quote.companyPlaceholder": "Enter your company name",
        "quote.email": "Email Address",
        "quote.phone": "Phone Number",
        "quote.stoneTypes": "Stone Type(s) of Interest",
        "quote.projectScope": "Project Scope",
        "quote.scopeResidential": "Residential",
        "quote.scopeCommercial": "Commercial",
        "quote.scopeHospitality": "Hospitality",
        "quote.scopeMultiUnit": "Multi-Unit",
        "quote.scopeOther": "Other",
        "quote.approxArea": "Approximate Area",
        "quote.areaPlaceholder": "e.g. 200 m²",
        "quote.timeline": "Estimated Timeline",
        "quote.timelineImmediate": "Immediate",
        "quote.timeline1to3": "1-3 Months",
        "quote.timeline3to6": "3-6 Months",
        "quote.timeline6to12": "6-12 Months",
        "quote.timeline12plus": "12+ Months",
        "quote.budget": "Budget Range",
        "quote.budgetOptional": "(Optional)",
        "quote.streetAddress": "Street Address",
        "quote.streetPlaceholder": "Project street address",
        "quote.city": "City",
        "quote.stateProvince": "State / Province",
        "quote.postalCode": "Postal Code",
        "quote.country": "Country",
        "quote.projectRequirements": "Project Requirements",
        "quote.requirementsPlaceholder": "Describe any specific veining requirements, block selection needs, or installation constraints...",
        "quote.termsText": "By submitting this form, you agree to our Terms of Service. Response within 24 hours.",

        "contact.heroTitle1": "Start a",
        "contact.heroTitle2": "Conversation.",
        "contact.heroDesc": "We invite you to discuss your architectural visions. Experience the weight, texture, and permanence of our curated stone collection firsthand.",
        "contact.firstName": "First Name",
        "contact.firstNamePlaceholder": "Enter your first name",
        "contact.lastName": "Last Name",
        "contact.lastNamePlaceholder": "Enter your last name",
        "contact.email": "Email Address",
        "contact.phone": "Phone Number",
        "contact.inquiryType": "Nature of Inquiry",
        "contact.selectOption": "Select an option",
        "contact.optionArch": "Architectural Project",
        "contact.optionRes": "Residential Design",
        "contact.optionComm": "Commercial/Retail",
        "contact.optionQuarry": "Quarry Direct",
        "contact.message": "Message",
        "contact.messagePlaceholder": "Tell us about your project vision...",
        "contact.submit": "Submit Inquiry",
        "contact.headquarters": "Headquarters",
        "contact.showroom": "Showroom",
        "contact.byAppointment": "By Appointment Only",
        "contact.pressMedia": "Press & Media",
        "contact.pressDesc": "For press kits, high-res lapidarium imagery, or interview requests.",
        "contact.contactPR": "Contact PR Team",
        "contact.quarryLocation": "Main Quarry",
        "contact.activeExtraction": "Active Extraction Site",

        "about.established": "Deep Heritage",
        "about.heroTitle1": "Sculpting",
        "about.heroTitle2": "Legacy",
        "about.heroTitle3": "Since The Beginning.",
        "about.heroDesc": "From the heart of the mountain to the soul of your space. We don't just extract stone; we curate history. Explore the origins of our Brutalist Elegance.",
        "about.exploreHeritage": "Explore Heritage",
        "about.quarryLot": "Main Quarry, Lot #842",
        "about.lapidariumTitle1": "The Digital",
        "about.lapidariumTitle2": "Lapidarium",
        "about.founderQuote": "We treat every slab not as construction material, but as a piece of art waiting to be unveiled. Our museum is the quarry, and our curators are the artisans who have shaped stone for over half a century.",
        "about.founderName": "Semih Dabağ",
        "about.founderRole": "Founder",
        "about.permanence": "Permanence",
        "about.permanenceDesc": "Stone outlasts empires. We ensure every cut honors the geological time trapped within the material.",
        "about.precision": "Precision",
        "about.precisionDesc": "Where the raw force of nature meets the millimeter accuracy of modern engineering.",
        "about.lapidariumExhibition": "Lapidarium Exhibition, 2023",
        "about.historyTitle": "Our History",
        "about.historySubtitle": "A Timeline Carved in Stone",
        "about.timeline1965": "Foundation",
        "about.timeline1965Title": "The Foundation",
        "about.timeline1965Desc": "Founded by Semih Dabağ in the Anatolian mountains with nothing but a chisel and a vision.",
        "about.timeline1995": "1995",
        "about.timeline1995Title": "Tech Integration",
        "about.timeline1995Desc": "Installation of the first industrial CNC machines, blending tradition with future tech.",
        "about.timelinePresent": "Present",
        "about.timelinePresentTitle": "Global Elegance",
        "about.timelinePresentDesc": "Operating in 12 countries, focusing on zero-waste initiatives and brutalist design language.",
        "about.methodologyTitle": "Our Methodology",
        "about.methodologySubtitle": "The Art & Science of Stone",
        "about.handTitle1": "The Hand",
        "about.handTitle2": "of the Master",
        "about.handDesc": "Honoring the imperfection that makes stone human. Every chisel mark tells a story of dedication and skill passed down through generations.",
        "about.machineTitle1": "The Machine",
        "about.machineTitle2": "of Precision",
        "about.machineDesc": "Achieving the impossible geometry of tomorrow. Our cutting-edge technology complements traditional methods, pushing the boundaries of design.",
        "about.ctaTitle1": "Ready to feel the",
        "about.ctaTitle2": "weight of history?",
        "about.bookVisit": "Book a Visit",
        "about.viewCollections": "View Collections",

        "common.viewDetails": "View Specifications",
        "common.enquire": "Enquire Now",

        "cta.title": "Start Your Project",
        "cta.subtitle": "From custom cuts for architectural masterpieces to bulk raw block orders for distributors.",
        "cta.requestQuote": "Request Quote",
        "cta.contactSales": "Contact Sales",

        "detail.productNotFound": "Product not found",
        "detail.home": "Home",
        "detail.collection": "Collection",
        "detail.series": "Series",
        "detail.ref": "Ref",
        "detail.description": "A masterpiece of geological history, offering a unique blend of durability and aesthetic depth. Sourced directly from our quarry, this stone features distinctive veining that makes every cut a one-of-a-kind work of art.",
        "detail.origin": "Origin",
        "detail.originValue": "Turkey",
        "detail.thickness": "Available Thickness",
        "detail.surfaceFinish": "Surface Finish",
        "detail.surfaceFinishValue": "Polished, Honed, Brushed",
        "detail.application": "Application",
        "detail.applicationValue": "Interior, Exterior, Wet Areas",
        "detail.orderSample": "Request Quote",
        "detail.shippingTitle": "Shipping & Delivery",
        "detail.shippingDesc": "Global shipping available. Crates are reinforced for maximum protection. Lead time varies by finish and quantity.",
        "detail.youMayLike": "You May Also Like",
        "detail.similarSpecimens": "Similar Specimens",
        "detail.viewAll": "View All",

        "notFound.badge": "Strata Missing",
        "notFound.title": "Lost in the Quarry?",
        "notFound.description": "The geological vein you are following seems to have ended abruptly. This specimen has not been excavated yet or has been moved to the deep archives.",
        "notFound.returnHome": "Return to Surface",
        "notFound.viewCollection": "View Collection",

        // Locations Page
        "locations.systemActive": "// Coordinate System: Active",
        "locations.title": "Our Locations",
        "locations.desc": "From the raw earth of the quarry to the refined silence of the gallery. Explore the physical touchpoints of our stone archive.",
        "locations.address": "Address",
        "locations.contact": "Contact",
        "locations.hours": "Hours",
        "locations.getDirections": "Get Directions",
        "locations.quarryName": "Afyon Quarry",
        "locations.quarryType": "Extraction Point",
        "locations.showroomName": "Konya Showroom",
        "locations.showroomType": "Gallery Space",
        "locations.hqName": "Ankara HQ",
        "locations.hqType": "Administration",
    },
    tr: {
        "nav.home": "Anasayfa",
        "nav.products": "Ürünler",
        "nav.locations": "Lokasyonlar",
        "nav.careers": "Kariyer",
        "nav.about": "Hakkımızda",
        "nav.contact": "İletişim",
        "nav.requestQuote": "TEKLİF İSTE",

        "hero.title": "Dağdan Gelen Mükemmellik",

        "hero.cta": "Koleksiyonu Keşfet",

        "intro.title": "DİJİTAL LAPİDARIUM",
        "intro.text": "Doğanın eşsiz sanatını yaşam alanlarınıza taşıyoruz. Her biri kendine has dokusu ve karakteriyle seçilmiş doğal taş koleksiyonumuz, mekanlarınıza zamansız bir zarafet ve sofistike bir atmosfer katıyor.",
        "intro.stat1Label": "YILLIK ÇIKARMA",
        "intro.stat2Label": "OCAK ALANI",
        "intro.stat3Label": "İHRACAT",
        "intro.stat3Unit": "ÜLKE",

        "catalog.curated": "Küratörlü Plakalar",
        "catalog.scroll": "Kataloğu Kaydır",

        "showroom.virtual": "Seemar Doğal Taş & Mermer",
        "showroom.title": "MERMER VE DOĞAL TAŞ KATALOĞUMUZU KEŞFEDİN",
        "showroom.text": "Mermer, traverten, oniks ve granit dahil tüm doğal taş koleksiyonumuzu keşfedin. Detaylı ürün katalogumuzda her taşın teknik özelliklerini, renk seçeneklerini ve uygulama alanlarını inceleyin.",
        "showroom.cta": "Kataloğu İncele",

        "projects.label": "PROJELER",
        "projects.title": "Mimari Şaheserler",
        "projects.viewAll": "Tüm Projeleri Gör",
        "projects.all": "Tümü",
        "projects.commercial": "Ticari",
        "projects.residential": "Konut",
        "projects.hospitality": "Konaklama",
        "projects.religious": "Dini Mimari",
        "projects.art": "Sanat & Heykel",
        "projects.pageDesc": "SeeMAR doğal taşlarının kullanıldığı prestijli mimari projelerimizi keşfedin. Kutsal mekanlardan ticari dönüm noktalarına, her proje işçilik ve kalıcılığın hikayesini anlatır.",
        "projects.filter": "Filtrele:",
        "projects.empty": "Bu kategoride proje bulunamadı.",
        "projects.featured": "Öne Çıkan",
        "projects.ctaTitle": "Aklınızda Bir Proje mi Var?",
        "projects.ctaDesc": "Ekibimizin premium Türk taşlarıyla mimari vizyonunuzu hayata geçirmesine izin verin.",
        "projects.ctaButton": "Projenize Başlayın",
        "projects.location": "Konum",
        "projects.year": "Yıl",
        "projects.materials": "Kullanılan Malzemeler",
        "projects.client": "Müşteri",
        "projects.viewProject": "Projeyi Görüntüle",
        "projects.backToProjects": "Projelere Dön",
        "projects.relatedProjects": "İlgili Projeler",
        "projects.aboutProject": "Bu Proje Hakkında",
        "projects.projectDetails": "Proje Detayları",
        "projects.projectNotFound": "Proje Bulunamadı",

        "catalog.label": "E-KATALOG",
        "catalog.title": "Ürün Katalogu",
        "catalog.desc": "Doğal taşlar, mermerler ve mimari malzemelerimizin tam koleksiyonunu dijital kataloğumuzda keşfedin.",
        "catalog.pdfTitle": "Seemar Ürün Katalogu 2024",
        "catalog.download": "PDF İndir",
        "catalog.loading": "Katalog yükleniyor...",
        "catalog.noteTitle": "Not",
        "catalog.noteText": "Bu dijital katalog standart koleksiyonumuza genel bir bakış sunar. Nadir örnekler, özel kesimler ve özel malzemeler için lütfen satış ekibimizle doğrudan iletişime geçin.",

        "products.collection": "Koleksiyon",
        "products.title": "Taş Kütüphanesi",
        "products.desc": "Cilalı mükemmelliğe rafine edilmiş ham kaos seçkimizi keşfedin. Her plaka, dünyamızın jeolojik tarihinde benzersiz bir sayfadır.",
        "products.filter": "Filtrele:",
        "products.empty": "Bu kategoride örnek bulunamadı.",
        "products.reset": "Filtreyi Sıfırla",
        "products.customTitle": "Özel Kesimler Mevcut",
        "products.customDesc": "Aradığınızı bulamıyor musunuz? Projenizin özel ihtiyaçlarına uygun özel kesimler, farklı boyutlar ve seçkin taş çeşitleri sunuyoruz.",
        "products.requestAccess": "Özel Teklif İste",

        // Product Categories
        "cat.marble": "MERMER ÇEŞİTLERİ",
        "cat.travertine": "TRAVERTEN ÇEŞİTLERİ",
        "cat.onyx": "ONİKS ÇEŞİTLERİ",
        "cat.limestone": "LİMESTONE ÇEŞİTLERİ",
        "cat.granite": "GRANİT ÇEŞİTLERİ",
        "cat.dolomite": "DOLOMİT ÇEŞİTLERİ",
        "cat.mosaic": "MOZAİK ÇEŞİTLERİ",
        "cat.splitface": "PATLATMA DOĞAL TAŞ",
        "cat.tumbled": "TAMBURLU TAŞ",
        "cat.sand": "ENDÜSTRİYEL KUM",
        "cat.all": "Tüm Koleksiyonlar",

        "careers.join": "Mirasımıza Katılın",
        "careers.heroDesc": "Taşın geleceğini sanatla işliyoruz. Brütalist hassasiyetin organik sanatla buluştuğu yer.",
        "careers.artTitle": "Kalıcılık Sanatı",
        "careers.artDesc1": "SeeMAR'da sadece taş kesmiyoruz; tarihi küratörlüğünü yapıyoruz. Kalıcılığın ağırlığını anlayan zanaatkarlar ve mühendisler arıyoruz.",
        "careers.artDesc2": "Kültürümüz, brütalist hassasiyet ve organik yaratıcılığın dengesidir. İster 5 eksenli bir CNC makinesi kullanın, ister bir Carrara plakasını elle parlatın, çalışmanız taşa kazınmış bir mirasa katkıda bulunur.",
        "careers.openings": "Açık Pozisyonlar",
        "careers.openingsDesc": "Dijital Lapidarium ekibine katılın.",
        "careers.apply": "Başvur",

        "footer.desc": "Doğanın ruhunu estetikle buluşturuyoruz. Taşa kazınmış bir miras, dünyanın en prestijli projelerine zamansız zarafet sunuyor.",
        "footer.explore": "Keşfet",
        "footer.company": "Şirket",
        "footer.social": "Sosyal",
        "footer.rights": "Tüm hakları saklıdır.",
        "footer.quarryHQ": "Ocak Merkezi",
        "footer.theCollection": "Koleksiyon",
        "footer.rareFinds": "Nadir Parçalar",
        "footer.projects": "Projeler",
        "footer.journal": "Günlük",
        "footer.sustainability": "Sürdürülebilirlik",
        "footer.privacyPolicy": "Gizlilik Politikası",
        "footer.termsOfUse": "Kullanım Koşulları",
        "footer.pdfCatalog": "PDF Katalog",

        "careers.precision": "Hassasiyet",
        "careers.heritage": "Miras",
        "careers.innovation": "İnovasyon",
        "careers.allRoles": "Tüm Pozisyonlar",
        "careers.artisans": "Zanaatkarlar",
        "careers.engineering": "Mühendislik",
        "careers.operations": "Operasyon",
        "careers.dontSeeVein": "Arananı bulamadın mı?",
        "careers.talentText": "Uzman kadromuza katılacak istisnai yetenekler arıyoruz. Portföy veya CV'nizi gönderin.",
        "careers.contactUs": "İletişime Geç",
        "careers.coverLetter": "Ön Yazı (İsteğe Bağlı)",
        "careers.coverLetterPlaceholder": "Bu pozisyon için neden uygun olduğunuzu anlatın...",
        "careers.breadcrumb": "Kariyer",
        "careers.jobDetails": "Pozisyon Detayları",
        "careers.division": "Bölümü",
        "careers.applyNow": "Şimdi Başvur",
        "careers.theRole": "Pozisyon Hakkında",
        "careers.responsibilities": "Sorumluluklar",
        "careers.qualifications": "Aranan Nitelikler",
        "careers.applyForPosition": "Bu Pozisyona Başvur",
        "careers.applyDesc": "SeeMAR ile kariyerinize başlamak için başvurunuzu gönderin.",
        "careers.firstName": "Ad",
        "careers.lastName": "Soyad",
        "careers.email": "E-posta Adresi",
        "careers.phone": "Telefon",
        "careers.linkedin": "LinkedIn Profili (İsteğe Bağlı)",
        "careers.resume": "Özgeçmiş / CV",
        "careers.uploadResume": "CV Yükle",
        "careers.submitApplication": "Başvuruyu Gönder",
        "careers.fileSizeError": "Dosya Boyutu Limiti Aşıldı (Maks 5MB)",
        "careers.aboutTeam": "Ekip Hakkında",
        "careers.defaultTeamDesc": "Tutkulu profesyonellerden oluşan ekibimize katılın.",
        "careers.keyBenefits": "Yan Haklar",
        "careers.benefit1": "Kapsamlı Sağlık Sigortası",
        "careers.benefit2": "Emeklilik Planı",
        "careers.benefit3": "Organik Yemek",
        "careers.benefit4": "Yıllık Eğitim Bütçesi",
        "careers.shareRole": "Bu İlanı Paylaş",
        "careers.similarRoles": "Benzer Pozisyonlar",
        "careers.similarRolesDesc": "Dijital Lapidarium'daki diğer fırsatları keşfedin.",
        "careers.viewAllOpenings": "Tüm İlanları Görüntüle",
        "careers.detailsOnApplication": "Detaylar başvuru sonrası paylaşılacaktır.",

        "quote.title": "Teklif İste",
        "quote.desc": "Mimari vizyonunuza özel detaylı bir teklif almak için proje gereksinimlerinizi belirtin. Ocak teslim malzemeler için özel teklifler sunuyoruz.",
        "quote.step1": "İletişim Bilgileri",
        "quote.step2": "Proje Detayları",
        "quote.step3": "Proje Konumu",
        "quote.step4": "Ek Notlar",
        "quote.submit": "Teklif İsteğini Gönder",
        "quote.fromQuarry": "Ocaktan",
        "quote.rawMaterial": "Ham Malzeme.",
        "quote.refinedElegance": "İşlenmiş Zarafet.",
        "quote.needAssistance": "Yardıma mı İhtiyacınız Var?",
        "quote.assistanceDesc": "Taş küratörlerimiz mimari projelerde seçim konusunda size yardımcı olmaya hazır.",
        "quote.collection": "Koleksiyon",
        "quote.fullName": "Ad Soyad",
        "quote.fullNamePlaceholder": "Adınızı ve soyadınızı girin",
        "quote.companyName": "Şirket Adı",
        "quote.companyPlaceholder": "Şirket adınızı girin",
        "quote.email": "E-posta Adresi",
        "quote.phone": "Telefon Numarası",
        "quote.stoneTypes": "İlgilenilen Taş Türü",
        "quote.projectScope": "Proje Kapsamı",
        "quote.scopeResidential": "Konut",
        "quote.scopeCommercial": "Ticari",
        "quote.scopeHospitality": "Otelcilik",
        "quote.scopeMultiUnit": "Toplu Konut",
        "quote.scopeOther": "Diğer",
        "quote.approxArea": "Tahmini Alan",
        "quote.areaPlaceholder": "örn. 200 m²",
        "quote.timeline": "Tahmini Süre",
        "quote.timelineImmediate": "Acil",
        "quote.timeline1to3": "1-3 Ay",
        "quote.timeline3to6": "3-6 Ay",
        "quote.timeline6to12": "6-12 Ay",
        "quote.timeline12plus": "12+ Ay",
        "quote.budget": "Bütçe Aralığı",
        "quote.budgetOptional": "(İsteğe Bağlı)",
        "quote.streetAddress": "Sokak Adresi",
        "quote.streetPlaceholder": "Proje sokak adresi",
        "quote.city": "Şehir",
        "quote.stateProvince": "İl / İlçe",
        "quote.postalCode": "Posta Kodu",
        "quote.country": "Ülke",
        "quote.projectRequirements": "Proje Gereksinimleri",
        "quote.requirementsPlaceholder": "Özel damar gereksinimleri, blok seçimi ihtiyaçları veya kurulum kısıtlamalarını belirtin...",
        "quote.termsText": "Bu formu göndererek Kullanım Şartlarımızı kabul etmiş olursunuz. 24 saat içinde yanıt verilecektir.",

        "contact.heroTitle1": "Bir",
        "contact.heroTitle2": "Sohbete Başlayın.",
        "contact.heroDesc": "Mimari vizyonlarınızı tartışmaya davet ediyoruz. Özenle seçilmiş taş koleksiyonumuzun ağırlığını, dokusunu ve kalıcılığını bizzat deneyimleyin.",
        "contact.firstName": "Ad",
        "contact.firstNamePlaceholder": "Adınızı girin",
        "contact.lastName": "Soyad",
        "contact.lastNamePlaceholder": "Soyadınızı girin",
        "contact.email": "E-posta Adresi",
        "contact.phone": "Telefon Numarası",
        "contact.inquiryType": "Talep Türü",
        "contact.selectOption": "Bir seçenek seçin",
        "contact.optionArch": "Mimari Proje",
        "contact.optionRes": "Konut Tasarımı",
        "contact.optionComm": "Ticari/Perakende",
        "contact.optionQuarry": "Doğrudan Ocak",
        "contact.message": "Mesaj",
        "contact.messagePlaceholder": "Proje vizyonunuz hakkında bilgi verin...",
        "contact.submit": "Talebi Gönder",
        "contact.headquarters": "Merkez",
        "contact.showroom": "Showroom",
        "contact.byAppointment": "Sadece Randevu ile",
        "contact.pressMedia": "Basın & Medya",
        "contact.pressDesc": "Basın kitleri, yüksek çözünürlüklü görseller veya röportaj talepleri için.",
        "contact.contactPR": "Halkla İlişkiler Ekibi",
        "contact.quarryLocation": "Merkez Ocak",
        "contact.activeExtraction": "Aktif Çıkarım Sahası",

        "about.established": "Köklü Miras",
        "about.heroTitle1": "Doğal Taşın",
        "about.heroTitle2": "Mirasını",
        "about.heroTitle3": "Geleceğe Taşıyoruz.",
        "about.heroDesc": "Dağın kalbinden yaşam alanınızın ruhuna. Biz sadece taş çıkarmıyoruz; tarihi küratörlük yapıyoruz. Brütalist Zarafetimizin kökenlerini keşfedin.",
        "about.exploreHeritage": "Mirası Keşfet",
        "about.quarryLot": "Merkez Ocak, Lot #842",
        "about.lapidariumTitle1": "Dijital",
        "about.lapidariumTitle2": "Lapidaryum",
        "about.founderQuote": "Her plakayı inşaat malzemesi olarak değil, ortaya çıkmayı bekleyen bir sanat eseri olarak görüyoruz. Müzemiz ocak, küratörlerimiz ise yarım asırı aşkın süredir taşı şekillendiren ustalar.",
        "about.founderName": "Semih Dabağ",
        "about.founderRole": "Kurucu",
        "about.permanence": "Kalıcılık",
        "about.permanenceDesc": "Taş imparatorluklardan daha uzun yaşar. Her kesimin malzemenin içinde hapsolmuş jeolojik zamana saygı göstermesini sağlıyoruz.",
        "about.precision": "Hassasiyet",
        "about.precisionDesc": "Doğanın ham gücünün modern mühendisliğin milimetre hassasiyetiyle buluştuğu yer.",
        "about.lapidariumExhibition": "Lapidaryum Sergisi, 2023",
        "about.historyTitle": "Tarihçemiz",
        "about.historySubtitle": "Taşa İşlenmiş Bir Zaman Çizelgesi",
        "about.timeline1965": "Kuruluş",
        "about.timeline1965Title": "Kuruluş",
        "about.timeline1965Desc": "Semih Dabağ tarafından Anadolu dağlarında sadece bir keskiyle ve vizyonla kuruldu.",
        "about.timeline1995": "1995",
        "about.timeline1995Title": "Teknoloji Entegrasyonu",
        "about.timeline1995Desc": "İlk endüstriyel CNC makinelerinin kurulumu, geleneği gelecek teknolojisiyle harmanlama.",
        "about.timelinePresent": "Günümüz",
        "about.timelinePresentTitle": "Küresel Zarafet",
        "about.timelinePresentDesc": "12 ülkede faaliyet göstererek sıfır atık girişimlerine ve brütalist tasarım diline odaklanma.",
        "about.methodologyTitle": "Metodolojimiz",
        "about.methodologySubtitle": "Taşın Sanatı ve Bilimi",
        "about.handTitle1": "Ustanın",
        "about.handTitle2": "Eli",
        "about.handDesc": "Taşı insancıl kılan kusursuzluğa saygı. Her keskı izi, nesillerden nesillere aktarılan özveri ve becerinin hikayesini anlatır.",
        "about.machineTitle1": "Hassasiyetin",
        "about.machineTitle2": "Makinesi",
        "about.machineDesc": "Geleceğin imkansız geometrisini başarmak. Son teknoloji ekipmanlarımız geleneksel yöntemleri tamamlayarak tasarımın sınırlarını zorlar.",
        "about.ctaTitle1": "Tarihin ağırlığını",
        "about.ctaTitle2": "hissetmeye hazır mısınız?",
        "about.bookVisit": "Ziyaret Rezervasyonu",
        "about.viewCollections": "Koleksiyonları Görüntüle",

        "common.viewDetails": "Teknik Özellikler",
        "common.enquire": "Hemen Sor",

        "cta.title": "Projenizi Başlatın",
        "cta.subtitle": "Mimari şaheserler için özel kesimlerden distribütörler için toplu ham blok siparişlerine kadar.",
        "cta.requestQuote": "Teklif İste",
        "cta.contactSales": "İletişime Geç",

        "detail.productNotFound": "Ürün bulunamadı",
        "detail.home": "Anasayfa",
        "detail.collection": "Koleksiyon",
        "detail.series": "Serisi",
        "detail.ref": "Ref",
        "detail.description": "Jeolojik tarihin bir şaheseri, dayanıklılık ve estetik derinliğin benzersiz bir harmanını sunuyor. Doğrudan ocağımızdan elde edilen bu taş, her kesimi eşsiz bir sanat eseri yapan ayırt edici damarlara sahiptir.",
        "detail.origin": "Köken",
        "detail.originValue": "Türkiye",
        "detail.thickness": "Mevcut Kalınlık",
        "detail.surfaceFinish": "Yüzey İşlemi",
        "detail.surfaceFinishValue": "Cilalı, Honlanmış, Fırçalanmış",
        "detail.application": "Uygulama Alanı",
        "detail.applicationValue": "İç Mekan, Dış Mekan, Islak Alanlar",
        "detail.orderSample": "Teklif İste",
        "detail.shippingTitle": "Kargo ve Teslimat",
        "detail.shippingDesc": "Küresel kargo mevcuttur. Kasalar maksimum koruma için güçlendirilmiştir. Teslim süresi, işleme ve miktara göre değişir.",
        "detail.youMayLike": "Bunları da Beğenebilirsiniz",
        "detail.similarSpecimens": "Benzer Örnekler",
        "detail.viewAll": "Tümünü Gör",

        "notFound.badge": "Katman Bulunamadı",
        "notFound.title": "Ocakta mı Kayboldunuz?",
        "notFound.description": "Takip ettiğiniz jeolojik damar aniden sona ermiş görünüyor. Bu örnek henüz çıkarılmamış veya derin arşivlere taşınmış olabilir.",
        "notFound.returnHome": "Yüzeye Dön",
        "notFound.viewCollection": "Koleksiyonu Görüntüle",

        // Locations Page
        "locations.systemActive": "// Koordinat Sistemi: Aktif",
        "locations.title": "Lokasyonlarımız",
        "locations.desc": "Ocağın ham topraklarından galerinin rafine sessizliğine. Taş arşivimizin fiziksel temas noktalarını keşfedin.",
        "locations.address": "Adres",
        "locations.contact": "İletişim",
        "locations.hours": "Çalışma Saatleri",
        "locations.getDirections": "Yol Tarifi Al",
        "locations.quarryName": "Afyon Ocağı",
        "locations.quarryType": "Çıkarım Noktası",
        "locations.showroomName": "Konya Showroom",
        "locations.showroomType": "Galeri Alanı",
        "locations.hqName": "Ankara Merkez",
        "locations.hqType": "Yönetim",
    }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
    const [language, setLanguage] = useState<Language>('tr');

    const t = (key: string) => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};